VanshKing30/FoodiesWeb

- README.md
Readme updated and all possible sections added to make it ready for open source program.
> Readme updated and contribution guidelines added

- src/components/Navbar.jsx
Fixes #10 
small screens:
- Responsive
- Animated using framer motion
- Preserved all actions
> Updated Navbar.

- src/components/Navbar.jsx
Reverts VanshKing30/FoodiesWeb#22
> Revert "Updated Navbar."

- server/populateDB.js
- **Fixed Missing Variables:**
- Added `accountType` variable in the creation of canteens and students where it was missing.
- Updated the creation of canteens and students according to the `accountType` variable.
- **Updated Dish Variables:**
- Added the `dish` variable in the creation of breakfast, lunch, and dinner.
- Renamed `dishName` variable to `dish` in breakfast, lunch, and dinner creations.
- **Added Dishes and Dish IDs:**
- Added new dishes in the breakfast, lunch, and dinner creation functions.
- Ensured that dish IDs are correctly assigned to each dish.
- Created variables `accountType` for canteens and students where missing and updated creation accordingly.
- Updated dish variables in breakfast, lunch, and dinner creations, changing `dishName` to `dish`.
- Added new dishes …
> Updated populate.js now can be used perfectly for automation.

- package.json
- src/components/CanteenList.jsx
- src/components/Navbar.jsx
- src/pages/About.jsx
- src/pages/News.jsx
This pull request addresses two main issues:
1. It fixes the navbar position to the top.
2. It adds a Framer Motion UseScroll feature to enhance the navbar functionality.
- Fixed the navbar position to remain at the top regardless of scroll position.
- Implemented Framer Motion UseScroll feature to enhance user experience and interaction with the navbar.
- Ensured responsiveness of the navbar based on the latest commit.
Describe any testing that has been performed to ensure the changes are functioning as expected. Include details of any edge cases considered.
> added scroll motion along with fixed navbar

- src/components/ModalForm.jsx
- src/pages/Signup.jsx
> Fixed Typos in Toast-issue#17

- package.json
- src/pages/Signup.jsx
Using JS regex i have implemented a check to verify strong password
below are the images after changes
After the user have entered Strong Password ->
> Feat: Strong Password will only be accepted Ref-#37

- README.md
Any feedback or suggestions are welcome 🍃
> Update README.md for better understanding

- src/App.js
- src/pages/Login.jsx
- src/pages/Signup.jsx
Update the sign up page by adding link to render again on login if already account was created.
> Add login link on signup page

- src/pages/About.jsx
Fixes #62 
Changed ui as suggested
- Preserved all actions
- Responsive
> Updated UI:About Us page

- server/middlewares/auth.js
- server/routes/canteen.js
i have added two middleware functions, `auth` and `isCanteen`, to important routes. 
The `auth` middleware function is responsible for authenticating users, ensuring that only logged-in users can access certain routes. 
The `isCanteen` middleware function checks if the authenticated user has the 'Canteen' role, thus providing an additional layer of authorization. This ensures that only users with the 'Canteen' role can access certain canteen-specific routes.
These changes improve the security 
if normalUser call (http://localhost:4000/api/v1/663f39be531290d9e2050601/breakfast/add) then below message got
if Canteen manager call (http://localhost:4000/api/v1/663f39be531290d9e2050601/breakfast/add) then below message got
same as other api works
> Fix: Resolved issue #12 by adding middlewares

- src/pages/MenuPage.jsx
Add condition before provide feedback before submit if feedback section is empty it get notification for provide feedback otherwise it show feedback submitted notification
> BUG:Feedback Submitted Notification Even though Feedback not given

- package.json
- src/pages/About.jsx
@VanshKing30 , Animation is added to About US section. Kindly review the PR.
Here video is provided for animation:-
https://github.com/VanshKing30/FoodiesWeb/assets/129666293/a1fa86dd-41de-4c63-9bb1-b5ed2dc6184b
> Animation added to About us Section

- package.json
- server/config/database.js
- src/App.js
- src/components/Loader/Loader.css
- src/components/Loader/Loader.jsx
- src/pages/About.jsx
- src/pages/Home.jsx
- src/pages/MenuPage.jsx
- src/pages/News.jsx
- src/pages/SectionPage.jsx
- src/pages/Signup.jsx
Loader Feature Implemented. 
Also one addtional route created at frontend **/loader** to check how loader is populating on the screen
> Loader Feature Implemented

- server/controllers/Auth.js
- server/middlewares/auth.js
- server/package.json
- server/routes/student.js
- server/server.js
Hey @VanshKing30, I have completed integrating authentication functionalities for the users. 
Now, our system can successfully execute : 
1. Login for both students and Canteen
2. Logout for both students and Canteen
3. Reset the Password for both types of users
Note - I have used **cookie parser middleware in the auth middleware** for extracting cookies.
1. Login
See, here you can see the token in response to the login request.
So, this **token would be removed as we hit the logout route**.
3. Logout
See, the tokens are successfully removed.
4. Reset Password
Note - I have only added screenshots of Student section but Canteen portion is also done.
Please, provide if any more changes required!!
> Added Logout and Reset Password succesfully

- Create Contributing.md
fixes #88
Created Contributing.md file and added necessary details required to be followed in-order to contribute.
> Created Contributing.md File

- src/components/Navbar.jsx
Hey @VanshKing30, Can you review this PR solving issue #100.
Centered text for NavElement:
Aligned the mobile NavBar to the center and removed on-hover grey bg from logout button:
> Responsive Navbar issue 100

- .github/pull_request_template.md
solve issue #96 
please merge the pr i forgot to rise the PR and also my exams are running
sorry sir @VanshKing30 🥲😥
> doc_add_pr_template

- src/pages/About.jsx
The overflow of About Page has been removed. Now the layout error is resolved for the About Page.
Fixes #141 
- [] A documentation update
- [] Others(mentioned in the issue number)
> fix-#141: Layout Error in About Page.

- src/index.css
Fixes #101 
Before change:
After change:
- Preserved all actions and functionality of other components
- Fixed for browsers: chrome, firefox, edge, opera and other browsers.
- Tested locally.
> Fixes UI bug

- src/components/Modal.jsx
- src/pages/SectionPage.jsx
Fixes #133  And #130
Problem : UI BUG
--> Fix canteen info card
--> Breakfast, Lunch And Dinner Card Don't Have Responsiveness On Mobile Devices/Medium Screen
> Fix canteen info card And Responsiveness Of Breakfast,Lunch and  dinner card

- .dockerignore
- .github/workflows/build.yml
- .github/workflows/deploy_backend.yml
- .github/workflows/deploy_frontend.yml
- Dockerfile
- server/.dockerignore
- server/Dockerfile
- src/pages/Signup.jsx
"I have added CI and CD pipelines in the workflow folder, which are helpful for continuous integration and continuous deployment.
##Command for deploying a repository on Docker
- Create two Docker images on Docker Hub.
- Create an access token on Docker Hub.
- Create two secret credentials on GitHub:
- DOCKER_USERNAME: Docker username
- DOCKER_PASSWORD: Access token of Docker Hub
- Finally, add the Docker username and Docker image name in both deploy.yml files."
> add ci and cd pipelines

- src/components/CanteenCard.jsx
- src/pages/MenuPage.jsx
Fixes #95 
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] My changes generate no new warnings
- [ X] I have added …
> added max-width in canteen-cards

- server/controllers/Auth.js
- server/models/session.js
- src/pages/Login.jsx
- src/pages/Signup.jsx
Fixes #73
**_Test B Describe here (if Required)_**
- session's schema
- student and canteen user login logic with proper use of sessions
- logout logic for both student and canteen users
- Session Schema: Defined in Mongoose.
- Session Creation: Handled during login.
- Session Validation: Ensures tokens are valid and sessions exist.
- Session Expiration: Managed automatically by …
> Fixed: Adding sessions to website #73

- .github/workflows/autocomment-iss-close.yml
Fixes #198 
It has been tested in a 'Test' repository and is working fine.
> added workflow as per issue #198

- .github/workflows/greetings.yml
Bot added for automate greeting whenever issue/PR is made
Fixes #185 
> Create automate bot

- README.md
- package.json
- server/package.json
- src/pages/Signup.jsx
Fixes #215
Readme file changes of setting up environmental variables.
I tested it in my local device
> Readme files updates

- src/pages/Login.jsx
- src/pages/Signup.jsx
Signup and Sign-in bug fixed . 
Problem was that somehow base API was commented out which is deployed API ( in frontend ) .
Still localhost/:4000 api was running. ( **I have commented out this API and uncommented BASE API** )
**ADD LOADER** ,  so that user can known that ok it is doing some work in progress so that user will wait . 
Else it will continuously click the submit button and API fetching will load Up
There can be **_Formatting difference between your code and my code JUST DUE TO VSCODE setup_** No do not get that i have made so many changes
**JUST ADDED LOADER AS YOU HAVE DONE IN OTHER FILES**
**UNCOMMENT THE BASE URL**
https://github.com/VanshKing30/FoodiesWeb/assets/105008414/c9392e80-d98e-4456-9f01-de0c42085379
**AFTER ADDING LOADER AND WITH PROPER  BASE API CALLING OF …
> Fixed - #213 Sign up and sign in will work as well as loader added 

- src/components/Footer.jsx
I have updated the Footer and I have also made it responsive sir.
@VanshKing30 @hustlerZzZ can you please check and let me know if any changes are required?
> Updated Footer

- package.json
- server/config/database.js
- server/server.js
- src/index.js
- src/pages/Login.jsx
- src/pages/Signup.jsx
When the data is being fetched for the signup and login processes, the respective buttons should be disabled now. Additionally, instead of displaying "Login" or "Signup," the buttons are displaying "Loading..." to enhance the user interface and user experience (UI/UX).
Fixes #174 
> Solved issue 174

- package.json
- src/App.js
- src/components/Footer.jsx
- src/components/Navbar.jsx
- src/pages/About.jsx
- src/pages/Home.jsx
- src/pages/News.jsx
- src/themeContext.js
- tailwind.config.js
Successfully Implemented the Dark and Light theme feature as per the need if you need further changes do let me know!
Elevate user experience with our dynamic mode toggle feature, allowing users to effortlessly switch between dark and light themes according to their preference and ambient lighting conditions. With this feature, users can customize their viewing experience, whether they prefer a sleek, modern dark mode for reduced eye strain in low-light environments or a vibrant light mode for enhanced readability during the day. Our intuitive toggle seamlessly adapts the interface, ensuring consistency and comfort across all interactions. Experience versatility in design with our dynamic mode toggle, offering a personalized touch to every user's journey.
> Light and dark theme

- src/components/Navbar.jsx
- src/components/NewsCard.jsx
Extra gap reduced  between mobile nav and logo component
Fixes #245
> Extra gap reduced  between mobile nav and logo component

- src/components/NewsCard.jsx
Fixes #183
**_Test B Describe here (if Req
ured)_**
> Default news card image added

- src/pages/Signup.jsx
Hey !! I have resolved the small bug from the Sign Up page .
Fixes  #263
> Resolved small bug in SignUp page

- src/pages/Login.jsx
- src/pages/Signup.jsx
This PR addresses an alignment issue with the login/sign-up page messages on mobile screens. The issue caused messages to be misaligned or displayed incorrectly on smaller devices. This fix ensures that all messages are properly aligned and displayed correctly on mobile devices.
Fixes #260 
Before
After
> Solved issue 260

- src/components/Navbar.jsx
Hello Project Admin,
I added Icons to Navbar
Solved - #269
> Added Icons to Navbar

- src/components/Footer.jsx
Successfully updated the theme switching of the footer in light and dark mode
Fixes #281 
Locally tested the website after making the changes and everything is fine.
footer in Light mode
footer in Dark mode
> updated footer theme in dark mode

- server/controllers/canteenController.js
- src/App.css
- src/pages/AddFoodItem.jsx
- src/pages/Foodlist.jsx
- src/pages/Login.jsx
- src/pages/SectionPage.jsx
-ADDED A MINI NAV BAR ON CANTEEN INTERFACE
-ADDED UI FOR PRODUCT LIST
-ADDED AND UPDATED BACKEND FOR DELETING FOOD ITEM
Fixes # 252
- [X ] New feature (non-breaking change which adds functionality)
Log in as canteen add item in menu go on product list and try to remove them
https://github.com/VanshKing30/FoodiesWeb/assets/101548649/67f6f6a9-979f-4862-aee3-5559769d1939
- [X ] I have commented my code, particularly in hard-to-understand areas
- [X ] I have made corresponding changes to the documentation
- [ X] My changes generate no new warnings
- [X ] I have added tests that prove my fix is effective or …
> Feat:In canteen The canteen should able to see the items they have added plus they can remove them #252

- src/components/Footer.jsx
Social Contact details of the project admin and project mentor are added to the footer section.
They redirect to their respective linkedin pages and helps in building their connections and network!!
Fixes #282 
Locally tested the feature in the project and everything is fine
Footer 
> Contact details added in the footer

- src/pages/About.jsx
This pull request addresses the alignment issues on the About page when viewed on mobile screens. The changes include updating the CSS to ensure proper alignment and responsiveness. The motivation for this change is to improve the user experience by ensuring that all elements are properly aligned and easily readable on smaller screens.
Fixes #290 
The following tests were conducted to verify the changes:
- Tested the About page on multiple mobile devices (both Android and iOS) to ensure proper alignment of elements.
- Used browser developer tools to simulate various screen sizes and ensure responsiveness.
- Verified that no other parts of the website were affected by the CSS …
> Solved issue 290

- src/components/CanteenCard.jsx
In the canteen card menu I have mentioned every section with name and change the size of it 
Fixes # (issue) #203 
> gave every section the name

- .github/pull_request_template.md
- src/components/Navbar.jsx
- src/pages/Login.jsx
- src/pages/Signup.jsx
fixed the github markdown pull request page
Fixes #319 
> Spell error

- src/index.js
- src/pages/Login.jsx
- tailwind.config.js
Enhancement in the login page by adding some CSS border-bottom. It enhance UI.
Fixes #328 
- [X ] Bug fix (non-breaking change which fixes an issue)
- [ X] Refactor code
-[ X] Documentation update
- [ X] Other (mentioned in the issue number)
closes issue no. #328 
with the label and level of GSSOC.
> Enhancement done in  the Login/Register page with borders.

- src/components/Navbar.jsx
- src/pages/Signup.jsx
-Fixed NavBAr
Fixes #331 
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ x] I have performed a self-review of my code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] I have added tests …
> Feat:Want to Fix Nav Bar #331

- src/pages/About.jsx
- src/pages/Login.jsx
BUG:When Someone click on About US He is Getting Looged Out #337
Fixes #337 
- [ y] Bug fix (non-breaking change which fixes an issue)
https://github.com/VanshKing30/FoodiesWeb/assets/101548649/491ad2ac-fb9a-4daf-8a6d-c8500c2b5403
- [ y] My code follows the style guidelines of this project
- [ y] I have performed a self-review of my code
- [y ] I have commented my code, particularly in …
> BUG:When Someone click on About US He is Getting Looged Out #337

- src/components/CanteenCard.jsx
- src/pages/AddFoodItem.jsx
- src/pages/EditProfile.jsx
- src/pages/Foodlist.jsx
- src/pages/Login.jsx
- src/pages/SectionPage.jsx
Fixes #338 
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] I have commented my code, particularly in …
> Feat:Dark Mode Not Working in Canteen End #338

- src/components/FoodCard.jsx
- src/pages/MenuPage.jsx
Feat: Lets Update menu make them using Cards #320
updated Menu-Page Now Showing Cards
Fixes # 320
- [ y] New feature (non-breaking change which adds functionality)
https://github.com/VanshKing30/FoodiesWeb/assets/101548649/422a044b-dd95-4910-a1d1-e643608b058e
- [ y] My code follows the style guidelines of this project
- [y ] I have performed a self-review of my code
- [y ] I have commented my …
> Feat: Lets Update menu make them using Cards #320

- server/controllers/Auth.js
- server/server.js
- src/pages/Login.jsx
This pull request addresses the issue of successful login not redirecting to the home page. The changes include updating the login logic to ensure that users are correctly navigated to the home page upon successful authentication. Additionally, the handling of the token storage has been improved to facilitate seamless redirection.
Fixes #350 
- Attempt login with valid credentials.
- Verify redirection to the home page.
- Check local storage for the presence of the token.
- Mock authentication service. …
> Solved issue 350

- .github/workflows/autocomment-iss-close.yml
- .github/workflows/close-old-issue.yml
- .github/workflows/close-old-pr.yml
- server/controllers/canteenController.js
- server/models/Review.js
- server/models/feedback.js
- server/routes/canteen.js
- server/routes/reviews.js
- src/App.css
- src/components/AddReview.jsx
- src/components/Feedback.jsx
- src/components/Navbar.jsx
- src/components/Reviews.jsx
- src/pages/Home.jsx
- src/pages/MenuPage.jsx
- src/pages/Signup.jsx
@VanshKing30 
Completed the task.
It is necessary for the user to know the general review of public. For this it is necessary to have a common public review section for each restaurant where we can complement and maybe based on ratings, we can search a restaurant/ canteen as well based on the ratings via search box later.
> Public review

- src/components/Navbar.jsx
Fixes #357 
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, …
> Feat:Canteen Navbar should be Different #357

- server/controllers/canteenController.js
- src/components/Navbar.jsx
- src/pages/Home.jsx
The logout button on the application was rendering the signup page without removing the user token from local storage. This fix ensures that the user token is properly removed upon logout, leading to a seamless transition to the signup page.
Fixes #305 
- Added code to remove the user token from local storage when the logout button is clicked.
- Ensured the logout action triggers a redirect to the signup page after clearing the token.
- Updated relevant components to reflect these changes.
Please …
> Solved issue 305

- src/App.css
- src/components/Feedback.jsx
- src/index.css
- src/pages/MenuPage.jsx
I have added a BEM naming convention 
I found that the classes is being written in app.css and index.css so i changed according to that with the corresponsiding usage of classes in jsx file like menupage.jsx and feedback.jsx 
Fixes #384 
**_Test A: Describe here_** This will be tested by regular refreshing the target page on which i did the changes 
> Added BEM Naming convention

- src/App.css
- src/components/Navbar.jsx
- src/pages/MenuPage.jsx
Fixed Logout Functionality
Fixes #371 
- [X ] New feature (non-breaking change which adds functionality)
**Hey @hustlerZzZ  in this i have fixed all the preexisting errors in image as well so can you please assign it level 2**
- [X ] I have commented my code, particularly in …
> Feat:Logout Button Not Working It is just Redirecting #371

- src/App.css
- src/components/FoodCard.jsx
- src/components/Navbar.jsx
- src/pages/Foodlist.jsx
- src/pages/MenuPage.jsx
Feat:Want to Update Ui Foodlist page as Cards #372
Updated ui as Card
Fixes #372 
- [y ] New feature (non-breaking change which adds functionality)
Before ::
After::
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the …
> Feat:Want to Update Ui Foodlist page as Cards #372

- src/pages/Login.jsx
- src/pages/News.jsx
This pull request addresses the issue of extra space between the heading "Trending Food and Health News" and the new cards on the News Page. The extra space has been removed to improve the visual alignment and overall user experience of the page.
Fixes #390 
> Solved issue 390

- src/components/CanteenCard.jsx
- src/components/CanteenList.jsx
1. Made Card Responsive
2. Assigned Fixed Width And Height to cards and handled them according to screen size to ensure responsiveness
3. Fixed Canteen Image Overflowing issue
4. Handled Condition Where Canteen has Big Name
Fixes #398 
- [ X] I have performed a self-review …
> Feat:Want to Update Canteen Cards #398

- public/index.html
Fixes #413 
Kindly let me know if there are any changes to be made.
> appropriate meta tags are added

- src/components/CanteenCard.jsx
- src/components/Footer.jsx
- src/components/Navbar.jsx
- tailwind.config.js
Fix invalid href attributes in Navbar, Footer, CanteenCard component
Summary of Changes:
Resolved an issue where the components in the application had invalid href attributes, ensuring correct links and accessibility.
Motivation and Context:
The fix addresses the incorrect usage of href attributes in the Navbar, Footer, CanteenCard component, which could lead to accessibility issues and incorrect navigation behavior.
Related Issue:
Fixes # (replace with your issue number)
Dependencies:
- React Router for navigation handling
- Tailwind CSS for styling adjustments
Manual testing was conducted to verify the following:
**_Test A: Verified correct navigation to different pages using Navbar,Footer,CanteenCard links._**
**_Test B: Checked for console errors related to href attributes._**
> Fix invalid href attributes

- server/controllers/canteenController.js
- server/models/canteenLoginInfo.js
- server/routes/canteen.js
- src/components/AddSocialMediaModal.jsx
- src/pages/EditProfile.jsx
- src/pages/Home.jsx
- src/pages/Login.jsx
- src/pages/SectionPage.jsx
- src/pages/Signup.jsx
This pull request addresses the addition of frontend and backend support for managing canteen social media links. Specifically, it allows users to add, display, and check for the existence of social media links (Instagram, Facebook, YouTube, LinkedIn) for canteens. The primary motivation is to enhance the user experience by providing a way to manage these links directly from the user interface.
Fixes #392 
**Test A: Fetch Canteen Data**
- Verify that the canteen data is fetched correctly from the backend.
- Check that the canteenSocialMediaLinks are displayed properly. …
> Add frontend and backend support for canteen social media links

- public/index.html
- server/controllers/feedbackController.js
- server/models/studentfeeback.js
- server/routes/student.js
- src/pages/Login.jsx
- src/pages/MenuPage.jsx
Wrote backend of studentfeedback form
ensured student is verified 
Fixes #421 
- [ x] New feature (non-breaking change which adds functionality)
https://github.com/VanshKing30/FoodiesWeb/assets/101548649/57499e10-0067-46cb-9f64-4aebb6cd720b
- [ X] I have commented my code, particularly in …
> Feat:Want to Write Backend Of FeedBack Page Of Canteens #421

- src/App.js
- src/components/Footer.jsx
- src/pages/MenuPage.jsx
This PR fix the issue of extra space between feedback input and menu list.
Fixes #431 
- Open the menu page.
- Navigate to the feedback section.
- Verify that the extra space between the feedback input and the menu list has been removed.
> solved issue 431

- src/App.css
Since there is a overwriting of password in password input and I faced it in only edge so I added only few line of CSS which hide the eye icon which was overwritten.
Fixes # (Bugfix for Password overwriting )
I added only few line of CSS which hide the eye icon which was overwritten.
addition of CSS in App.css
i run it in  my browser  below i have attached a video of testing 
https://github.com/user-attachments/assets/a8f4d565-a291-405f-9b7e-e49a05383910
> BugFix for Password overwriting 

- src/pages/Signup.jsx
> Bug in Name Section of Sign Up Page is solved

- src/pages/EditProfile.jsx
Fixes #487 
- [ X] Bug fix (non-breaking change which fixes an issue)
https://github.com/user-attachments/assets/0923f95b-b502-44aa-af67-52cb1c443600
- [X ] I have …
> Feat:Canteen profile is not Editable #487

- server/controllers/canteenController.js
- server/models/canteenLoginInfo.js
- server/routes/canteen.js
This pull request introduces the backend functionality to allow students to add ratings and feedback for canteens. The changes include:
- Creation of a Feedback model to store feedback and ratings given by students.
- Updates to the Canteen model to dynamically calculate and update the overall rating based on feedback.
- Addition of a new controller method to handle adding feedback and updating the overall rating.
- Introduction of a new route to facilitate adding feedback for canteens.
Fixes #494 
Please describe the tests that you ran to verify your changes. Provide …
> Solved issue 494

- server/server.js
This pull request addresses the CORS problem encountered during login. The issue was causing the frontend to fail when making requests to the backend due to CORS policy restrictions. By configuring the CORS middleware in the backend, this problem has been resolved.
Fixes #496 
- Set the FRONTEND_URL environment variable in the .env file to the URL of the frontend …
> Solved cors issue in server

- src/components/Blog/newss.jsx
- src/pages/News.jsx
News page heading should be visible in both dark and light modes.
Fixes #509 
> Solved issue 509
