src/App.js
src/pages/NotFound.jsx

As per the issue, a custom 404 error page had to be made. The page has been added in the name 'NotFound.jsx' under the 'pages' folder. The following are the screenshots:
WHEN NOT HOVERING
WHEN HOVER
Kindly, check the PR and merge if requirements are matched.

Custom 404 page

---

src/pages/Login.jsx
src/pages/Signup.jsx

The eye toggling is showing opposite behaviour like when eye is open then the pass will be hidden and on slash eye the pass will be shown to the user . so i fixed it by changing the position of slash eye icon with the eye icon in the ternary operator . It includes the fixes for both signup and login page .
Fixes #156 
it will be tested by clicking multiple times to the eye icon to check its functionality .

fixed Eye toggling shows Opposite behaviour 

---

src/pages/About.jsx

Fixes the stretching of image element in about page.
**Resolves** #175

Fixed about-page img stretching on window resize

---

src/pages/News.jsx

Aligned the news elements horizontally and vertically in with the main content section of `News` page. Fixed the margin for the title. 
Fixes #219 

Centering news elements

---

src/pages/About.jsx

Removed unwanted white spaces by decreasing bottom margin
Fixes #197 
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] I have …

Removed unwanted white spaces from About page

---

src/components/Footer.jsx

Fixes #196 
- [ x] Bug fix (non-breaking change which fixes an issue)
Changed the anchor tag to useNavigation function for scroll on click.
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is …

Fixed the path to About link in the footer 

---

server/controllers/Auth.js
server/middlewares/auth.js
src/components/ModalForm.jsx
src/pages/AddFoodItem.jsx
src/pages/Home.jsx
src/pages/Login.jsx
src/pages/MenuPage.jsx
src/pages/SectionPage.jsx
src/pages/Signup.jsx

-There Are several Changes make fixed port so that new user can easily setup this projects backend
-Updated Login and Signup logic
-On Canteen Side Added form for user to Add Menu Items
Fixes #232 
- [x ] New feature (non-breaking change which adds functionality)
- [x ] Refactor Code
https://github.com/VanshKing30/FoodiesWeb/assets/101548649/ade99aac-5287-4f3f-8a0a-fafcfe333c34
- [X ] My code follows the style guidelines of this …

Feat:Want To Add Backend Canteen menu item #232

---

src/index.css

Modified marginal properties of the heading of news page such that it is aligned properly with navbar
Fixes  #239 
tested the project in local environment and it is working.

Aligned heading of News page properly such that "Navbar overlapping heading of News page issue" is Resolved

---

server/controllers/Auth.js
src/pages/MenuPage.jsx

This pull request fixes the alignment of the menu button to improve the UI. Specifically, the component was adjusted to ensure proper alignment and structure, making it more visually appealing.
Fixes #229 
The menu button was misaligned, leading to a suboptimal user experience. This fix ensures the button is properly centered and styled, enhancing the overall interface.

Redesigned Menu Cards

---

src/pages/Signup.jsx

fix: :lock: removed `env` link from console

---

.github/workflows/greetings.yml

Updated `greetings` workflow action token naming convention
:warning: make sure to add a new personal access token in repository secrets with name `GH_TOKEN` and give access to `issues` and `pull requests`
Fixes #257 
I have tested this workflow on my repo: https://github.com/aayushchugh/workflows/issues/1

fix: greetings workflow access token naming convention

---

src/pages/Login.jsx
src/pages/Signup.jsx

Fixes #255
Tested this in localhost and it's working fine now
https://github.com/VanshKing30/FoodiesWeb/assets/115611556/176b90f0-eb83-4df1-a4a4-6bab577b8f8f
- [X ] My changes generate no new warnings

Fixed the signup and login issue #255

---

server/config/cloudinaryConfig.js
server/controllers/canteenController.js
server/middleware/multer.middleware.js
server/models/canteenLoginInfo.js
server/routes/canteen.js
server/server.js
src/App.js
src/components/CanteenCard.jsx
src/pages/AddFoodItem.jsx
src/pages/EditProfile.jsx
src/pages/Login.jsx
src/pages/SectionPage.jsx
src/pages/Signup.jsx

ADDED A Fully PROFILE Page 
-Updated Ui
-Added  Update Profile backed
-Fixed Cloudinary config
-updated Schema
Fixes # 253
- [ x] New feature (non-breaking change which adds functionality)
you can check it by updating profile
https://github.com/VanshKing30/FoodiesWeb/assets/101548649/1bacb86e-8ebd-419b-99f8-83281727a0f1
- [x ] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit …

Feat:Profile page For Canteen #253

---

src/pages/Login.jsx

Fixes #274
After logging in it's showing user logged in successfully
- [ X] Bug fix (non-breaking change which fixes an issue)
https://github.com/VanshKing30/FoodiesWeb/assets/115611556/bc8af724-13fb-49de-92f5-4cfe5be848ac
- [X ] My code follows the style …

Fixes message in login page

---

src/pages/Login.jsx
src/pages/Signup.jsx

This change addresses and fixes issue #182, which involves displaying the error message from the backend in a toast notification upon login and signup failure.
Fixes #182 

Solved issue 182

---

src/components/FloatBtn/FloatBtn.css
src/components/FloatBtn/FloatBtn.jsx
src/pages/About.jsx
src/pages/Home.jsx
src/pages/News.jsx

- Added  `FloatBtn` component in `Home` , `About` and `News` pages
- Added hovering effect for the floating button as well
- On clicking the floating button, users can easily scroll back to top
Fixes #173 
It has been tested on my local machine
https://github.com/VanshKing30/FoodiesWeb/assets/115717746/56b92926-3fe7-421c-a57a-e9079cb76c9b

Added floating button to scroll back to top

---

src/pages/Login.jsx

**This implementation includes:**
1. Centered "Forgot Password" link using flex justify-center.
2. "Remember Me" checkbox with appropriate HTML elements.
No new dependencies are required for these changes.
Fixes #302 
**Manual UI Inspection:**
1. Opened the application in a local development environment.
2. Navigated to the login page.
3. Visually inspected the layout to ensure the "Forgot Password" link is centered.
4. Verified that the "Remember Me" checkbox appears correctly and is functional.
**Checkbox Functionality Test:**
1. Checked the behavior of the "Remember Me" checkbox by selecting and deselecting it.
2. Verified that the checkbox's state is correctly tracked.
**Responsive Design Test:**
Resized the browser window to various …

Added the Remember me button in authentication successfully

---

server/controllers/Auth.js
server/package.json
src/pages/Signup.jsx

This pull request adds a "Confirm Password" field to the signup page to enhance user experience by ensuring that users enter their desired password correctly during registration. Additionally, it includes backend validation to ensure the password and confirm password fields match before creating a new account. This enhancement will reduce user errors and improve overall security.
Fixes  #287
1.Frontend Changes:
Signup Component:
Added a new input field for "Confirm Password" in the signup form.
Implemented a visibility toggle for the confirm password field similar to the password field.
2.Backend Changes:
Auth Controller:
Added validation logic to check if the password and confirm password fields match before proceeding with account creation.
If the passwords do not match, the server …

[Bug]:"Confirm Password" field added in signup page

---

server/controllers/Auth.js
src/App.js
src/authContext.js
src/pages/About.jsx
src/pages/Home.jsx
src/pages/Login.jsx
src/pages/News.jsx
src/pages/Signup.jsx

This update restricts access to the Home and About pages, ensuring that only logged-in users can access these pages. The implementation leverages the Context API to manage authentication state and conditionally renders components based on the user's authentication status.
Fixes #304 
- Attempted to access the Home and About pages without logging in.
- Verified that the user is …

Solved issue 304

---

server/controllers/canteenController.js
server/routes/canteen.js
src/components/Modal-update.js
src/pages/Foodlist.jsx

-Added Backend For Editing Menu Item
-Added modal
-Updated FoodList Component
Fixes # 310
- [X ] New feature (non-breaking change which adds functionality)
-Add Items And then click on edit icon
https://github.com/VanshKing30/FoodiesWeb/assets/101548649/57b0c34b-1f87-480f-b665-f7f533cc3e4d
- [ x] I have performed a self-review of my code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [ x] My …

Feat:In FoodList we Can add option to Edit FoodItem Name for Canteen #310

---

src/App.css
src/components/Navbar.jsx
src/index.css

The header has been enhanced to include a more attractive and stylish UI/UX. A line animation has been added to the navigation items on hover, which changes color according to the current theme (light or dark mode). This improvement aims to make the header visually appealing and interactive while maintaining the original positions and colors of the elements.
Fixes #306 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration:
- Manual testing was conducted by navigating through the application to ensure that the line animation appears correctly on hover for each navigation item.
- Verified the color change …

Enhanced Header

---

src/components/Navbar.jsx
src/pages/Rateus.jsx

This pull request adds the functionality of dark mode to the **Rate-us** page. Additionally, this also change the color of the logout button in the navbar WRT on the mode (dark / light).
changes made:
- removed the background image
- changed the background color of the Rate-us form
- the logout button now changes WRT mode (dark / light)
Fixes #289 
Manual trail and error is done to get the color pallet matching with existing pallet, in both dark and light modes.

update Rate-us and Log-out in navbar

---

src/components/Navbar.jsx
src/pages/Login.jsx
src/pages/Signup.jsx

Resolved minor issues.
Fixes #317 
Self tested in local machine

Visibility button

---

server/controllers/Auth.js

Fixed conflict markers in Auth.js
Fixes # 321
- [ X] Bug fix (non-breaking change which fixes an issue)
- [ X] Refactor Code

Fixed conflict markers in Auth.js

---

src/pages/Rateus.jsx

Hello Project Admin
I added Toastify Message - Solved #330 
https://github.com/VanshKing30/FoodiesWeb/assets/161804629/b0fa236d-5d1c-4833-b4e6-d24a8c24f3dd

Added Toastify Message 

---

src/pages/ContactUs.jsx

Improved ui for contact page
Fixes #349 
Code is tested Locally 

feat: Improve ui for the contact page

---

src/components/NewsCard.jsx
src/pages/Login.jsx
src/pages/News.jsx

This pull request addresses the issue of limiting the character count in the news card descriptions on the News Page. A "Read More" button has been added to enable users to expand and view the full description if it exceeds a specified length.
Fixes #391 
Before 
After

Solved issue 391

---

src/pages/AddFoodItem.jsx
src/pages/EditProfile.jsx
src/pages/Login.jsx
src/pages/SectionPage.jsx
src/pages/Signup.jsx

Enhanced canteen profile page
Fixes #393 
Before
After

Solved issue 393

---

src/pages/AddFoodItem.jsx
src/pages/SectionPage.jsx

1. Fixed Oveflowing Issue
2. Made Responsice
3. Fixed Icons Alingment
Fixes #396
- [ X] I have commented my code, particularly in hard-to-understand areas
- [ X] I have made corresponding changes to the documentation
- [ X] …

Feat:Want to fix UI of Add Product Page #396

---

src/components/Modal-update.js
src/pages/Foodlist.jsx

Fixes #434 
1. Fixed Updation Logic
2. Converted Ui To Cards
3. Made Sure Canteen End Cant Edit food Item
4. Removed Unecesarry Code
5. optimzed Solution
**Actually SomeOne Handled Merge Conflics Wrongly so There was Both Old and new Code** So Fixed That
- [X ] Bug fix (non-breaking change which fixes an issue)
- [X ] Refactor code
- [X ] Documentation update
- [X ] Other (mentioned in the issue number)
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce …

Feat:Error in updating Food items from Canteen End + This should be in Cards #434

---

src/pages/ContactUs.jsx

Fixes #444 
This pull request adds validation to notify users when they attempt to submit an empty form. The following changes were made:
Implemented a check in the handleEmailSubmit function to validate required fields.
Added validation in the handleSaveToDB function to ensure no required fields are left empty.
Displayed alert messages to inform users of missing required fields.
- [X ] Bug fix (non-breaking change which fixes an issue)

Validate and Alert Users for Empty Form Submissions

---

server/controllers/feedbackController.js
server/routes/student.js
src/pages/FeedbackList.jsx
src/pages/SectionPage.jsx

Fixes # 448
https://github.com/user-attachments/assets/100022d5-f244-4a59-8d1c-c90866b1b581
- [ X] I …

Feat:Canteen Should able to see Feedback Given to Them by User (UI +Integration) #448

---

README.md
server/.env.example
server/routes/errorHandlers.js

Summary of Changes:
Added a .env.example file to provide a template for environment variables used in the project.
Included placeholders for Cloudinary credentials, Google OAuth credentials, JWT secret, email settings, MongoDB connection string, React app base URL, and Unsplash API key.
Fixes #474 
Adding a .env.example file helps new contributors understand the required environment variables and how to configure them for local development. This improves the onboarding process and ensures consistency in environment setups.
This change doesn’t require specific tests since it involves adding a sample configuration file.
Test A: Verified that the .env.example file includes all necessary environment variables and provides clear instructions.
Test …

Added env.example File for Environment Variable Configuration

---

src/components/CanteenCardSkeleton.jsx
src/components/CanteenList.jsx

Fixes #479 
- [] New feature (non-breaking change which adds functionality)
- [] Other (mentioned in the issue number) …

Feat:Want to Add Skeletons In all the Cards #479

---

src/pages/Contributors.js

I have enhanced the UI in such a way : 
- Fixed the dark mode colors correctly now it is changing its color according to the dark mode 
- Added Number of contributions did by each user 
- Converted cards to rectangle to show all details
- Justified all content properly at center 
Fixes #484  
Tested by repeatedly refreshing the page and changes 

Enhanced The UI of the contributions page 

---

package.json
src/components/Blog/newss.jsx

I have changed the news section sin following ways :
Added Colored Heading 
Added seach functonality 
Added Fade up animation with framer motion 
Fixes #481 
Please assign 
if found it suitable for that
https://github.com/user-attachments/assets/c677e1f5-394a-49d3-a73c-6244ae908cfa

I have created the News Section

---

src/components/Blog/newss.jsx
src/pages/Home.jsx
src/pages/News.jsx

This update enhances the search functionality within the menu page of the application, enabling users to efficiently search for dishes across breakfast, lunch, and dinner categories. The previous implementation had limitations in filtering and displaying relevant search results, which has been addressed in this update.
Fixes #510 
- Search Functionality: Tested the search …

Enhace search bars

---

server/controllers/canteenController.js
server/models/canteenLoginInfo.js
server/routes/canteen.js
src/App.js
src/pages/AddTiming.jsx
src/pages/EditProfile.jsx

This pull request implements the frontend and backend functionality for adding and managing canteen availability on a day-wise basis. The frontend allows users to set morning, afternoon, and evening availability times for each day of the week. The backend is updated to handle these time slots correctly by accepting data in the required format.
Fixes #512 
**_Test B: …

Solved issue 512
